services:
  # BASE DE DATOS
  db:
    image: postgres:15-alpine
    container_name: monitor-db-local
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: monitor_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d monitor_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

  # TU API (SPRING BOOT)
  api:
    build: . # Esto buscará un 'Dockerfile' en la raíz de tu proyecto Java
    container_name: monitor-api-local
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/monitor_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data_local: