name: cloud-gateway
services:
  vpn-server:
    image: linuxserver/wireguard:latest
    env_file:
      - .env
    container_name: vpn-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - SERVERURL=${SERVER_PUBLIC_IP}
      - SERVERPORT=${SERVER_PORT}
      - PEERS=${PEER_1}# Nombres de tus clientes
      - PEERDNS=auto
      - INTERNAL_SUBNET=${INTERNAL_SUBNET}
      - ALLOWEDIPS=${SERVER_ALLOWED_IPS:-0.0.0.0/0}
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
      - "443:443"
      - "80:80"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    network_mode: "service:vpn-server"
    volumes:
      # Configuraciones Nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      # Certificados SSL
      - ./html:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - vpn-server
    restart: unless-stopped