
name: cloud-gateway
services:
  vpn-server:
    image: linuxserver/wireguard:latest
    env_file:
      - .env  # Cambiar a .env.prod en Produccion
    container_name: vpn-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE # Opcional, pero ayuda si el kernel del host lo soporta
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - SERVERURL=${SERVER_PUBLIC_IP} # O tu dominio (ej. vpn.miempresa.com)
      - SERVERPORT=${SERVER_PORT}
      - PEERS=${PEER_1}# Nombres de tus clientes
      - PEERDNS=auto
      - INTERNAL_SUBNET=${INTERNAL_SUBNET} # La red privada del túnel
      - ALLOWEDIPS=${SERVER_ALLOWED_IPS:-0.0.0.0/0}
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules # Para usar módulos del kernel si están disponibles
    ports:
      - 51820:51820/udp # IMPORTANTE: Abrir este puerto UDP en el Firewall de AWS
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Configuraciones Nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      # Certificados SSL
      # - ./nginx/cert:/etc/nginx/certs:ro
    depends_on:
      - vpn-server
    restart: always
  